### ISSUE TITLE
Parallax doesn't work when I'm routed to the page with it but works when I refresh the very page where it is

### ISSUE THREAD

**Issue by Coookiez** [pixelcog/parallax.js#261]
So the project is written in React.js.
I have a Main component which shows me the welcome page with navigation bar. When I'm clicking on a button to switch the view to let's say About.js (here the parallax-window elements are rendered) I only have blank gaps: https://imgur.com/a/qKvBUCM
However when I refresh that page (About.js) the parallax works perfectly fine: https://imgur.com/a/4Yx0tkv
untill I click some button to route me to another page (say the Main.js) - the parallax image stays on top of everything else even though there are no elements that belong to "parallax-window" class: https://imgur.com/a/bVqxa1B
Routing was done using HashRouter component, standard NavLinks exact to="/path" and exact path="/path".

Here's the code of aforementioned About.js class: https://gist.github.com/Coookiez/55f9dbc6c314366ee8c09bd1bbb87ab7

Any ideas how to make it work appropriately?

**Comment by wstoettinger** [comment]
as far as my knowledge of React goes, it modifies the DOM tree directly without reloading the page. Please keep in mind, that parallax-mirror and parallax-slider elements get injected into the DOM (or moved to, depending on the method you used) in different places than the parallax-window. they probably stay there while routing and don't get destroyed.

For the first problem: have you tried firing the resize trigger after the routing is completed?
```javascript
jQuery(window).trigger('resize').trigger('scroll');
```

For the second problem I would suggest to fire a destroy trigger before the routing takes place. This is only implemented in the v2 alpha version and I would appreciate to get some feedback on that feature and make the plugin ready for react.

**Comment by webmastervishal** [comment]
Sadly I am using a ready theme for my react project where they have used the version v1.4.2

do parallax('destroy') method works with v1.4.2?

**Comment by wstoettinger** [comment]
unfortunately not.

**Comment by webmastervishal** [comment]
I did migrate to v2.
Changed `data-image-src` to `data-src` to make it work.

Now, I am confused, if the plugin is injecting `parallax-mirror` and `parallax-slider`, what exactly `parallax('destroy') ` deletes?

And I am getting the error message that `$(....).parallax` is not a function.
And the document isn't clear enough to tell what exactly we are going to destroy.

**Comment by vesper8** [comment]
I also upgrade to v2 because I'm having the same issue.. works fine on reload but breaks when arriving via a SPA route

I upgraded to v2, made the modifications from data-image-src to data-src and the parallax is loading as it was before. But the same problem persists

I noticed that adding the destroy method doesn't seem to have any effect, but I also noticed that it doesn't remove the parallax-mirror copies.. so I need to continue removing those with $('.parallax-mirror').remove();

**Comment by wstoettinger** [comment]
"destroy" is supposed to remove the elements which get injected (parallax-mirror) and move the content of the parallax-slider back to where it was before initializing (i.e. the images should get static again). 

It's still experimental and unfortunately I don't have the React.js know-how but I would appreciate a pull request with suggested changes
